### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by sego1** [tinfoilboy/computare#1]
This is the output when I put make:
```
make[2]: *** There is no rule for constructing the '../pch.hpp' target, necessary for 'computare_pch/pch.hpp'.  High.
CMakeFiles/Makefile2:101: recipe for target 'CMakeFiles/computare.dir/all' failed
make[1]: *** [CMakeFiles/computare.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
My compiling steps are:
First, I clone the repository with **--recursive** and I get inside the folder, then
```
mkdir build; cd build
cmake ..
make
```
Is there something missing?

**Comment by tinfoilboy** [comment]
Hey! I'm sorry for the delay in responding to this, I never saw the notification.

I tried compiling this on my machine from a clean clone and I had the same error. This is now fixed in 28634b6. and will compile as expected.

Thank you for bringing this to my attention!
